### ISSUE TITLE
Colour gradient

### ISSUE THREAD

**Issue by onlytanmoy** [nfm886/skin.arctic.zephyr.2.resurrection.mod#23]
Hey mate, loving the colour gradient, definitely much pleasing on the eye as opposed to just a solid colour.
I was wondering if it will be possible to get the colour gradient during selection in this menu? It will be cool then :)
![Kodi_20210626_225409](https://user-images.githubusercontent.com/48493659/123526806-20ff2380-d6d2-11eb-94cc-fc594a01cdfa.png)

**Comment by nfm886** [comment]
Hmm... Is it possible? Of course :P But if I want it? I don't know :/
There may be some issues after adding colour gradient. We have to deal with font color then since on some gradients it's may be barely readable and we don't want it...
For now, I'm not sure if we can implement this. It require some investigation and thinking of implementation.

**Comment by onlytanmoy** [comment]
Hmm ok, it was just one of my ideas so thought of sharing with you :) will close this ticket.
