### ISSUE TITLE
focus frame

### ISSUE THREAD

**Issue by trkselim** [nfm886/skin.arctic.zephyr.2.resurrection.mod#6]
Thank you so much for your great work 

can make the focus frame for posters or landscape more thinner

**Comment by nfm886** [comment]
Hi!
Thanks for kind words!
I will consider this. Added to TODO list. When I will make some visual changes I should implement this. Or maybe add a switch to choose between 2 size of frames. Hmmm...

**Comment by nfm886** [comment]
Hi!
Just added options for choosing focus frame border size between two values, Bold (standard) and Thin (new) :)
If you want, you can test it right now by downloading this .zip file: https://github.com/nfm886/skin.arctic.zephyr.2.resurrection.mod/archive/refs/heads/main.zip

Enjoy ;)

**Comment by trkselim** [comment]
Thank you the frame size perfect 
Any plans for Netflix view for home widget 

have a nice day

**Comment by nfm886** [comment]
Yes, there are some plans :)
Since this is not easiest thing to do, it may take some time. I found that, this code is fit mostly with 3 views that are already implemented so I need to prepare it a little bit :)

I think we can close a ticket for now. Big thanks for your ideas to improve this awesome skin ;)
